# Generated by Django 3.0.2 on 2020-01-18 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_imageob'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageob',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
